Repository execom-eu/hawaii, pull requests merged in 2018-07, with the labels that each got.

#21 B feature oauth2
  .gitignore
  pom.xml
  src/main/java/eu/execom/hawaii/api/controller/GlobalExceptionHandler.java
  src/main/java/eu/execom/hawaii/api/controller/SignInController.java
  src/main/java/eu/execom/hawaii/model/LeaveProfile.java
  src/main/java/eu/execom/hawaii/model/Request.java
  src/main/java/eu/execom/hawaii/model/Team.java
  src/main/java/eu/execom/hawaii/model/User.java
  src/main/java/eu/execom/hawaii/security/SecurityConfiguration.java
  src/main/java/eu/execom/hawaii/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/db/changelog/initialDbSchema.xml
Labels: Backend

#22 B feature/team management
  src/main/java/eu/execom/hawaii/api/controller/TeamController.java
  src/main/java/eu/execom/hawaii/dto/TeamDto.java
  src/main/java/eu/execom/hawaii/repository/TeamRepository.java
  src/main/java/eu/execom/hawaii/service/TeamService.java
Labels: Backend

#24 B feature/leave profile management
  src/main/java/eu/execom/hawaii/api/controller/LeaveProfileController.java
  src/main/java/eu/execom/hawaii/dto/LeaveProfileDto.java
  src/main/java/eu/execom/hawaii/repository/LeaveProfileRepository.java
  src/main/java/eu/execom/hawaii/service/LeaveProfileService.java
Labels: Backend

#27 Added swagger
  README.md
  pom.xml
  src/main/java/eu/execom/hawaii/security/SecurityConfiguration.java
Labels: Backend

#28 B test/user service tests
  src/main/java/eu/execom/hawaii/api/controller/UserController.java
  src/main/java/eu/execom/hawaii/repository/UserRepository.java
  src/main/java/eu/execom/hawaii/service/UserService.java
  src/main/resources/application.properties
  src/test/java/eu/execom/hawaii/service/EntityBuilder.java
  src/test/java/eu/execom/hawaii/service/UserServiceTest.java
Labels: Backend

#34 B feature/leave type management
  src/main/java/eu/execom/hawaii/api/controller/AbsenceController.java
  src/main/java/eu/execom/hawaii/api/controller/LeaveProfileController.java
  src/main/java/eu/execom/hawaii/dto/AbsenceDto.java
  src/main/java/eu/execom/hawaii/model/absence/Absence.java
  src/main/java/eu/execom/hawaii/model/absence/AbsenceType.java
  src/main/java/eu/execom/hawaii/model/absence/BonusDays.java
  src/main/java/eu/execom/hawaii/model/absence/Leave.java
  src/main/java/eu/execom/hawaii/model/absence/Sickness.java
  src/main/java/eu/execom/hawaii/repository/AbsenceRepository.java
  src/main/java/eu/execom/hawaii/service/AbsenceService.java
  src/main/java/eu/execom/hawaii/service/LeaveProfileService.java
Labels: Backend

#20 F feature/redux introduction branch
  images/hawaii.png
  src/main/frontend/package.json
  src/main/frontend/src/App.js
  src/main/frontend/src/__test__/store/reducers/EmployeesReducer.test.js
  src/main/frontend/src/__test__/store/sagas/getEmployeeSaga.test.js
  src/main/frontend/src/__test__/store/selectors.test.js
  src/main/frontend/src/components/UserInfo.js
  src/main/frontend/src/components/UserInfoExtended.js
  src/main/frontend/src/components/header/InformationHeader.js
  src/main/frontend/src/components/header/TopHeader.js
  src/main/frontend/src/components/navigation/NavBar.js
  src/main/frontend/src/components/navigation/Sidebar.js
  src/main/frontend/src/store/Selectors.js
  src/main/frontend/src/store/Store.js
  src/main/frontend/src/store/actions/EmployeesActions.js
  src/main/frontend/src/store/reducers/EmployeesReducer.js
  src/main/frontend/src/store/reducers/index.js
  src/main/frontend/src/store/sagas/getEmployeeSaga.js
  src/main/frontend/src/store/services/user.js
  src/main/frontend/yarn.lock
Labels: Frontend

#37 B feature/request leave
  pom.xml
  src/main/java/eu/execom/hawaii/api/controller/AbsenceController.java
  src/main/java/eu/execom/hawaii/api/controller/GlobalExceptionHandler.java
  src/main/java/eu/execom/hawaii/api/controller/RequestController.java
  src/main/java/eu/execom/hawaii/dto/AbsenceDto.java
  src/main/java/eu/execom/hawaii/dto/RequestDto.java
  src/main/java/eu/execom/hawaii/model/Absence.java
  src/main/java/eu/execom/hawaii/model/Request.java
  src/main/java/eu/execom/hawaii/model/absence/Absence.java
  src/main/java/eu/execom/hawaii/model/absence/BonusDays.java
  src/main/java/eu/execom/hawaii/model/absence/Leave.java
  src/main/java/eu/execom/hawaii/model/absence/Sickness.java
  src/main/java/eu/execom/hawaii/model/enumerations/AbsenceType.java
  src/main/java/eu/execom/hawaii/repository/AbsenceRepository.java
  src/main/java/eu/execom/hawaii/repository/RequestRepository.java
  src/main/java/eu/execom/hawaii/service/AbsenceService.java
  src/main/java/eu/execom/hawaii/service/RequestService.java
  src/main/resources/db/changelog/initialDbSchema.xml
  src/test/java/eu/execom/hawaii/service/EntityBuilder.java
Labels: Backend

#40 Implemented session management
  src/main/java/eu/execom/hawaii/api/controller/SignInController.java
  src/main/java/eu/execom/hawaii/security/AuthenticationFilter.java
  src/main/java/eu/execom/hawaii/security/SecurityConfiguration.java
  src/main/java/eu/execom/hawaii/security/TokenStore.java
Labels: Backend

#43 B feature/approve request
  src/main/java/eu/execom/hawaii/api/controller/RequestController.java
  src/main/java/eu/execom/hawaii/model/Allowance.java
  src/main/java/eu/execom/hawaii/repository/AllowanceRepository.java
  src/main/java/eu/execom/hawaii/service/AllowanceService.java
  src/main/java/eu/execom/hawaii/service/RequestService.java
Labels: Backend

#49 Find all teams, "active" parameter isn`t required
  src/main/java/eu/execom/hawaii/api/controller/TeamController.java
  src/main/java/eu/execom/hawaii/service/TeamService.java
Labels: Backend

#50 B feature/google calendar integration
  .gitignore
  images/hawaii.png
  pom.xml
  src/main/java/eu/execom/hawaii/api/controller/RequestController.java
  src/main/java/eu/execom/hawaii/service/GoogleCalendarService.java
  src/main/java/eu/execom/hawaii/service/RequestService.java
  src/main/resources/application.properties
Labels: Backend

#53 Added members and approvers to TeamDto
  src/main/java/eu/execom/hawaii/dto/TeamDto.java
Labels: Backend

#51 B feature/view request history by user by date
  src/main/java/eu/execom/hawaii/api/controller/RequestController.java
  src/main/java/eu/execom/hawaii/repository/RequestRepository.java
  src/main/java/eu/execom/hawaii/service/RequestService.java
Labels: Backend

#54 Find all request by user without canceled
  src/main/java/eu/execom/hawaii/api/controller/RequestController.java
  src/main/java/eu/execom/hawaii/repository/RequestRepository.java
  src/main/java/eu/execom/hawaii/service/RequestService.java
Labels: backend
