Repository execom-eu/hawaii, pull requests merged in 2019-03, with the labels that each got.

#204 Fixes request cancellation
  src/main/java/eu/execom/hawaii/service/RequestService.java
  src/test/java/eu/execom/hawaii/service/RequestServiceTest.java
Labels: backend

#206 B fix/create team
  src/main/java/eu/execom/hawaii/HawaiiApplication.java
  src/main/java/eu/execom/hawaii/api/controller/TeamController.java
  src/main/java/eu/execom/hawaii/model/Team.java
  src/main/java/eu/execom/hawaii/model/User.java
  src/main/java/eu/execom/hawaii/repository/CustomizedTeamRepository.java
  src/main/java/eu/execom/hawaii/repository/CustomizedTeamRepositoryImpl.java
  src/main/java/eu/execom/hawaii/repository/TeamRepository.java
  src/main/java/eu/execom/hawaii/service/TeamService.java
  src/test/java/eu/execom/hawaii/service/TeamServiceTest.java
Labels: backend, fix

#209 Add message forwarding to client through GlobalExceptionHandler
  src/main/java/eu/execom/hawaii/api/controller/GlobalExceptionHandler.java
  src/main/java/eu/execom/hawaii/exceptions/ActionNotAllowedException.java
  src/main/java/eu/execom/hawaii/exceptions/InsufficientHoursException.java
  src/main/java/eu/execom/hawaii/exceptions/NotAuthorizedApprovalException.java
  src/main/java/eu/execom/hawaii/exceptions/RequestAlreadyCanceledException.java
  src/main/java/eu/execom/hawaii/service/AbsenceService.java
  src/main/java/eu/execom/hawaii/service/AllowanceService.java
  src/main/java/eu/execom/hawaii/service/LeaveProfileService.java
  src/main/java/eu/execom/hawaii/service/RequestService.java
  src/main/java/eu/execom/hawaii/service/TeamService.java
  src/main/java/eu/execom/hawaii/service/UserService.java
Labels: backend, enhancement

#208 Handle bonus request approval
  src/main/java/eu/execom/hawaii/dto/RequestDto.java
  src/main/java/eu/execom/hawaii/model/Absence.java
  src/main/java/eu/execom/hawaii/model/Request.java
  src/main/java/eu/execom/hawaii/model/User.java
  src/main/java/eu/execom/hawaii/service/RequestService.java
  src/main/resources/db/changelog/initialDbSchema.xml
Labels: backend

#205 f-fix/users-teams-crud-fixes
  .gitignore
  src/main/frontend/package.json
  src/main/frontend/src/components/calendar/calendarUtils.js
  src/main/frontend/src/components/employees/EmployeeInfo.js
  src/main/frontend/src/components/employees/Employees.js
  src/main/frontend/src/components/search-dropdown/SearchDropdown.js
  src/main/frontend/src/components/search-dropdown/search-results/EmployeeSearchResults.js
  src/main/frontend/src/components/tabs/Tabs.js
  src/main/frontend/src/components/teams/TeamItem.js
  src/main/frontend/src/components/teams/Teams.js
  src/main/frontend/src/index.js
  src/main/frontend/src/pages/Administration.js
  src/main/frontend/src/pages/CreateEmployee.js
  src/main/frontend/src/pages/CreateTeam.js
  src/main/frontend/src/pages/EditEmployee.js
  src/main/frontend/src/pages/EditTeam.js
  src/main/frontend/src/pages/Employee.js
  src/main/frontend/src/pages/Team.js
  src/main/frontend/src/store/actions/employeesSearchActions.js
  src/main/frontend/src/store/reducers/employeesReducer.js
  src/main/frontend/src/store/reducers/employeesSearchReducer.js
  src/main/frontend/src/store/reducers/reducers.js
  src/main/frontend/src/store/reducers/teamsReducer.js
  src/main/frontend/src/store/sagas/employeeSaga.js
  src/main/frontend/src/store/sagas/employeesSaga.js
  src/main/frontend/src/store/sagas/employeesSearchSaga.js
  src/main/frontend/src/store/sagas/sagas.js
  src/main/frontend/src/store/sagas/teamSaga.js
  src/main/frontend/src/store/sagas/teamsSaga.js
  src/main/frontend/src/store/sagas/toastrHelperSaga.js
  src/main/frontend/src/store/sagas/userSaga.js
  src/main/frontend/src/store/selectors.js
  src/main/frontend/src/store/services/employeesService.js
  src/main/frontend/src/store/services/request.js
  src/main/frontend/src/store/services/teamService.js
  src/main/frontend/src/styles/globalStyles.js
  src/main/frontend/yarn.lock
Labels: enhancement, fix, frontend

#210 B feature/maven profiles
  README.md
  pom.xml
Labels: backend, enhancement

#207 f-enhancement/gh-198-login-token-expiration
  src/main/frontend/src/layout/Login.js
  src/main/frontend/src/store/actions/authorizationActions.js
  src/main/frontend/src/store/reducers/getTokenReducer.js
  src/main/frontend/src/store/sagas/HOC/withErrorHandling.js
  src/main/frontend/src/store/sagas/employeeSaga.js
  src/main/frontend/src/store/sagas/employeesSaga.js
  src/main/frontend/src/store/sagas/getTokenSaga.js
  src/main/frontend/src/store/sagas/leaveTypesSaga.js
  src/main/frontend/src/store/sagas/personalDaysSaga.js
  src/main/frontend/src/store/sagas/publicHolidaySaga.js
  src/main/frontend/src/store/sagas/teamSaga.js
  src/main/frontend/src/store/sagas/teamsSaga.js
  src/main/frontend/src/store/sagas/userSaga.js
  src/main/frontend/src/store/services/getTokenRequest.js
Labels: enhancement, frontend

#213 B feature/users allowance used in previous year
  src/main/java/eu/execom/hawaii/dto/AllowanceWithoutYearDto.java
  src/main/java/eu/execom/hawaii/dto/LeaveProfileDto.java
  src/main/java/eu/execom/hawaii/model/Allowance.java
  src/main/java/eu/execom/hawaii/model/LeaveProfile.java
  src/main/java/eu/execom/hawaii/service/AllowanceService.java
  src/main/resources/db/changelog/initialDbSchema.xml
Labels: backend

#216 f-fix/team-edit-employee-search-dropdown
  src/main/frontend/src/pages/EditTeam.js
Labels: fix, frontend

#212 f-fix/changed-error-message-source
  src/main/frontend/src/store/sagas/HOC/withErrorHandling.js
Labels: fix

#225 Fix google calendar exceptions when creating request
  src/main/java/eu/execom/hawaii/service/RequestService.java
Labels: backend

#214 Create request internal server error fix
  src/main/frontend/src/pages/EditTeam.js
  src/main/frontend/src/store/sagas/HOC/withErrorHandling.js
  src/main/java/eu/execom/hawaii/service/RequestService.java
Labels: backend

#217 B fix/add pending in previous year to allowance
  src/main/java/eu/execom/hawaii/dto/AllowanceWithoutYearDto.java
  src/main/java/eu/execom/hawaii/model/Allowance.java
  src/main/java/eu/execom/hawaii/service/AllowanceService.java
  src/main/resources/db/changelog/initialDbSchema.xml
  src/test/java/eu/execom/hawaii/service/AbsenceServiceTest.java
  src/test/java/eu/execom/hawaii/service/AllowanceServiceTest.java
  src/test/java/eu/execom/hawaii/service/DayServiceTest.java
  src/test/java/eu/execom/hawaii/service/EntityBuilder.java
  src/test/java/eu/execom/hawaii/service/RequestServiceTest.java
Labels: backend, fix

#220 f-feature/gh-219-add-icons-sidebar
  src/main/frontend/src/components/UserInfoExtended.js
  src/main/frontend/src/components/common/ToggleSidebarButton.js
  src/main/frontend/src/components/common/mainLogo.js
  src/main/frontend/src/components/common/navigationLink.js
  src/main/frontend/src/components/navigation/Sidebar.js
  src/main/frontend/src/img/icons/icons archive white (24).png
  src/main/frontend/src/img/icons/icons dashboard white (24).png
  src/main/frontend/src/img/icons/icons execom calendar white (24).png
  src/main/frontend/src/img/icons/icons leave history white (24).png
  src/main/frontend/src/img/icons/icons leave white (24).png
  src/main/frontend/src/img/icons/icons logout white (24).png
  src/main/frontend/src/img/icons/icons team calendar white (24).png
  src/main/frontend/src/store/services/getTokenRequest.js
Labels: enhancement, frontend

#218 f-enhancement/gh-211-create-absence-request
  src/main/frontend/package.json
  src/main/frontend/src/components/calendar/CalendarContainer.js
  src/main/frontend/src/components/calendar/calendarUtils.js
  src/main/frontend/src/components/common/Radio.js
  src/main/frontend/src/components/dashboard/Dashboard.js
  src/main/frontend/src/components/modal/RequestModal.js
  src/main/frontend/src/components/modal/requests/RequestForm.js
  src/main/frontend/src/index.js
  src/main/frontend/src/store/actions/allowanceActions.js
  src/main/frontend/src/store/actions/modalActions.js
  src/main/frontend/src/store/actions/requestsActions.js
  src/main/frontend/src/store/reducers/allowanceReducer.js
  src/main/frontend/src/store/reducers/modalReducer.js
  src/main/frontend/src/store/reducers/reducers.js
  src/main/frontend/src/store/sagas/allowanceSaga.js
  src/main/frontend/src/store/sagas/requestsSaga.js
  src/main/frontend/src/store/sagas/sagas.js
  src/main/frontend/src/store/selectors.js
  src/main/frontend/src/store/services/allowanceService.js
  src/main/frontend/src/store/services/request.js
  src/main/frontend/src/store/services/requestsService.js
  src/main/frontend/src/styles/globalStyles.js
Labels: enhancement, frontend

#233 f-feature/gh-224-add-leave-profile-choice
  src/main/frontend/src/components/leaveProfiles/LeaveProfileItem.js
  src/main/frontend/src/components/leaveProfiles/LeaveProfiles.js
  src/main/frontend/src/layout/Panel.js
  src/main/frontend/src/pages/Administration.js
  src/main/frontend/src/pages/CreateEmployee.js
  src/main/frontend/src/pages/CreateLeaveProfile.js
  src/main/frontend/src/pages/EditEmployee.js
  src/main/frontend/src/pages/EditLeaveProfile.js
  src/main/frontend/src/pages/Employee.js
  src/main/frontend/src/pages/LeaveProfile.js
  src/main/frontend/src/store/actions/leaveProfileActions.js
  src/main/frontend/src/store/actions/leaveProfilesActions.js
  src/main/frontend/src/store/reducers/leaveProfileReducer.js
  src/main/frontend/src/store/reducers/leaveProfilesReducer.js
  src/main/frontend/src/store/reducers/reducers.js
  src/main/frontend/src/store/sagas/leaveProfileSaga.js
  src/main/frontend/src/store/sagas/leaveProfilesSaga.js
  src/main/frontend/src/store/sagas/sagas.js
  src/main/frontend/src/store/selectors.js
  src/main/frontend/src/store/services/leaveProfileService.js
  src/main/frontend/src/store/services/leaveProfilesService.js
Labels: enhancement, frontend

#235 Get public holidays reguestParams set default value and add id to public holiday dto
  src/main/java/eu/execom/hawaii/api/controller/PublicHolidayController.java
  src/main/java/eu/execom/hawaii/dto/PublicHolidayDto.java
Labels: backend

#228 Leave profile - service and database table
  src/main/java/eu/execom/hawaii/dto/LeaveProfileDto.java
  src/main/java/eu/execom/hawaii/model/LeaveProfile.java
  src/main/java/eu/execom/hawaii/model/enumerations/LeaveProfileType.java
  src/main/java/eu/execom/hawaii/service/LeaveProfileService.java
  src/main/resources/db/changelog/initialDbSchema.xml
  src/test/java/eu/execom/hawaii/service/EntityBuilder.java
  src/test/java/eu/execom/hawaii/service/LeaveProfileServiceTest.java
Labels: backend

#231 B-fix/gh-226-set-yearsOfService-for-created-user
  src/main/java/eu/execom/hawaii/api/controller/UserController.java
  src/main/java/eu/execom/hawaii/service/UserService.java
  src/test/java/eu/execom/hawaii/service/UserServiceTest.java
Labels: backend, fix

#236 Update public holiday - fix
  src/main/java/eu/execom/hawaii/api/controller/PublicHolidayController.java
Labels: backend

#238 Update users table fullname column
  src/main/resources/db/changelog/initialDbSchema.xml
Labels: backend

#240 f-feature/gh-239-years-crud
  src/main/frontend/src/components/years/YearItem.js
  src/main/frontend/src/components/years/Years.js
  src/main/frontend/src/layout/Panel.js
  src/main/frontend/src/pages/Administration.js
  src/main/frontend/src/pages/CreateYear.js
  src/main/frontend/src/pages/EditYear.js
  src/main/frontend/src/pages/Year.js
  src/main/frontend/src/store/actions/yearActions.js
  src/main/frontend/src/store/actions/yearsActions.js
  src/main/frontend/src/store/reducers/reducers.js
  src/main/frontend/src/store/reducers/yearReducer.js
  src/main/frontend/src/store/reducers/yearsReducer.js
  src/main/frontend/src/store/sagas/sagas.js
  src/main/frontend/src/store/sagas/yearSaga.js
  src/main/frontend/src/store/sagas/yearsSaga.js
  src/main/frontend/src/store/selectors.js
  src/main/frontend/src/store/services/yearService.js
  src/main/frontend/src/store/services/yearsService.js
Labels: enhancement, frontend

#227 B-feature/gh-222-show-requred-fields-in-swagger
  pom.xml
  src/main/java/eu/execom/hawaii/dto/AbsenceDto.java
  src/main/java/eu/execom/hawaii/dto/DayDto.java
  src/main/java/eu/execom/hawaii/dto/LeaveProfileDto.java
  src/main/java/eu/execom/hawaii/dto/PublicHolidayDto.java
  src/main/java/eu/execom/hawaii/dto/RequestDto.java
  src/main/java/eu/execom/hawaii/dto/TeamDto.java
  src/main/java/eu/execom/hawaii/dto/UserDto.java
  src/main/java/eu/execom/hawaii/dto/YearDto.java
  src/main/java/eu/execom/hawaii/model/Absence.java
  src/main/java/eu/execom/hawaii/model/LeaveProfile.java
  src/main/java/eu/execom/hawaii/model/PublicHoliday.java
  src/main/java/eu/execom/hawaii/model/Request.java
  src/main/java/eu/execom/hawaii/model/User.java
  src/main/java/eu/execom/hawaii/model/Year.java
  src/main/java/eu/execom/hawaii/security/SecurityConfiguration.java
  src/main/java/eu/execom/hawaii/service/AllowanceService.java
  src/main/java/eu/execom/hawaii/service/LeaveProfileService.java
  src/main/resources/db/changelog/initialDbSchema.xml
  src/test/java/eu/execom/hawaii/service/AllowanceServiceTest.java
  src/test/java/eu/execom/hawaii/service/RequestServiceTest.java
Labels: backend, enhancement

#230 Check if team with given name already exists when creating new team
  src/main/java/eu/execom/hawaii/repository/TeamRepository.java
  src/main/java/eu/execom/hawaii/service/TeamService.java
  src/test/java/eu/execom/hawaii/service/TeamServiceTest.java
Labels: backend

#247 Allowance without year dto attributes refactoring
  src/main/java/eu/execom/hawaii/dto/AllowanceWithoutYearDto.java
Labels: backend

#244 B feature/create allowance when creating new year
  src/main/java/eu/execom/hawaii/api/controller/YearController.java
  src/main/java/eu/execom/hawaii/dto/YearDto.java
  src/main/java/eu/execom/hawaii/model/User.java
  src/main/java/eu/execom/hawaii/repository/YearRepository.java
  src/main/java/eu/execom/hawaii/service/YearService.java
  src/main/resources/db/changelog/initialDbSchema.xml
  src/test/java/eu/execom/hawaii/service/YearServiceTest.java
Labels: backend
