Repository execom-eu/hawaii, pull requests merged in 2019-02, with the labels that each got.

#152 B feature/audit implementation
  images/hawaii.png
  pom.xml
  src/main/java/eu/execom/hawaii/api/controller/AuditInformationController.java
  src/main/java/eu/execom/hawaii/api/controller/RequestController.java
  src/main/java/eu/execom/hawaii/api/controller/TeamController.java
  src/main/java/eu/execom/hawaii/api/controller/UserController.java
  src/main/java/eu/execom/hawaii/dto/AuditInformationDto.java
  src/main/java/eu/execom/hawaii/model/AuditInformation.java
  src/main/java/eu/execom/hawaii/model/User.java
  src/main/java/eu/execom/hawaii/model/audit/Audit.java
  src/main/java/eu/execom/hawaii/model/audit/RequestAudit.java
  src/main/java/eu/execom/hawaii/model/audit/TeamAudit.java
  src/main/java/eu/execom/hawaii/model/audit/UserAudit.java
  src/main/java/eu/execom/hawaii/model/enumerations/AuditedEntity.java
  src/main/java/eu/execom/hawaii/model/enumerations/OperationPerformed.java
  src/main/java/eu/execom/hawaii/repository/AuditInformationRepository.java
  src/main/java/eu/execom/hawaii/service/AuditInformationService.java
  src/main/java/eu/execom/hawaii/service/RequestService.java
  src/main/java/eu/execom/hawaii/service/TeamService.java
  src/main/java/eu/execom/hawaii/service/UserService.java
  src/main/resources/db/changelog/initialDbSchema.xml
  src/test/java/eu/execom/hawaii/service/RequestServiceTest.java
  src/test/java/eu/execom/hawaii/service/TeamServiceTest.java
  src/test/java/eu/execom/hawaii/service/UserServiceTest.java
Labels: backend, enhancement

#153 fix/updated-readme
  README.md
  readme-gifs/credentials.gif
  readme-gifs/sql_script.gif
  src/main/resources/DataScript01022019.sql
Labels: fix

#159 Test Add - Fixed
  src/test/java/eu/execom/hawaii/service/AbsenceServiceTest.java
  src/test/java/eu/execom/hawaii/service/DayServiceTest.java
  src/test/java/eu/execom/hawaii/service/LeaveProfileServiceTest.java
  src/test/java/eu/execom/hawaii/service/TeamServiceTest.java
Labels: backend

#158 f-feature/gh-155-get-and-remove-team
  src/main/frontend/src/components/HOC/withResetOnNavigate.js
  src/main/frontend/src/components/common/navigationLink.js
  src/main/frontend/src/components/dashboard/Dashboard.js
  src/main/frontend/src/components/navigation/Sidebar.js
  src/main/frontend/src/components/teams/Teams.js
  src/main/frontend/src/layout/Login.js
  src/main/frontend/src/layout/Panel.js
  src/main/frontend/src/pages/Administration.js
  src/main/frontend/src/pages/Team.js
  src/main/frontend/src/store/actions/navigateActions.js
  src/main/frontend/src/store/actions/teamActions.js
  src/main/frontend/src/store/reducers/reducers.js
  src/main/frontend/src/store/reducers/teamReducer.js
  src/main/frontend/src/store/sagas/getTokenFromSessionStorageSaga.js
  src/main/frontend/src/store/sagas/sagas.js
  src/main/frontend/src/store/sagas/teamSaga.js
  src/main/frontend/src/store/selectors.js
  src/main/frontend/src/store/services/getTokenRequest.js
  src/main/frontend/src/store/services/teamService.js
Labels: enhancement, frontend

#162 f-enhancement/gh-161-overflow-inner-div
  src/main/frontend/src/components/employees/EmployeeInfo.js
  src/main/frontend/src/components/header/InformationHeader.js
  src/main/frontend/src/components/header/TopHeader.js
  src/main/frontend/src/components/tabs/Tabs.js
  src/main/frontend/src/layout/Panel.js
Labels: enhancement, frontend

#157 Users-GetAll Pagination
  src/main/java/eu/execom/hawaii/api/controller/UserController.java
  src/main/java/eu/execom/hawaii/repository/UserRepository.java
  src/main/java/eu/execom/hawaii/service/UserService.java
Labels: backend, enhancement

#174 Create db automatically if not existent, Liquibase fixed for staging.
  pom.xml
  src/main/resources/application.properties.example
  src/main/resources/liquibase.properties
Labels: backend, fix

#173 f-enhancement/gh-172-add-employee-update-page
  src/main/frontend/package.json
  src/main/frontend/src/components/employees/EmployeeInfo.js
  src/main/frontend/src/layout/Panel.js
  src/main/frontend/src/pages/EditEmployee.js
  src/main/frontend/src/store/actions/employeeActions.js
  src/main/frontend/src/store/reducers/employeeReducer.js
  src/main/frontend/src/store/sagas/employeeSaga.js
  src/main/frontend/src/store/services/employeeService.js
Labels: enhancement, frontend

#164 f-enhancement/gh-163-create-team-page
  src/main/frontend/src/components/teams/Teams.js
  src/main/frontend/src/layout/Panel.js
  src/main/frontend/src/pages/CreateTeam.js
  src/main/frontend/src/pages/Team.js
  src/main/frontend/src/store/actions/teamActions.js
  src/main/frontend/src/store/reducers/employeesReducer.js
  src/main/frontend/src/store/reducers/teamsReducer.js
  src/main/frontend/src/store/sagas/teamSaga.js
  src/main/frontend/src/store/services/employeesService.js
  src/main/frontend/src/store/services/teamService.js
  src/main/frontend/src/store/services/userService.js
  src/main/frontend/yarn.lock
Labels: enhancement, frontend

#166 f-enhancement/gh-165-add-edit-team-page
  pom.xml
  src/main/frontend/src/components/employees/EmployeeInfo.js
  src/main/frontend/src/components/employees/Employees.js
  src/main/frontend/src/components/teams/TeamItem.js
  src/main/frontend/src/components/teams/Teams.js
  src/main/frontend/src/pages/CreateEmployee.js
  src/main/frontend/src/pages/EditEmployee.js
  src/main/frontend/src/pages/EditTeam.js
  src/main/frontend/src/store/actions/employeeActions.js
  src/main/frontend/src/store/actions/employeesAction.js
  src/main/frontend/src/store/actions/teamActions.js
  src/main/frontend/src/store/reducers/employeeReducer.js
  src/main/frontend/src/store/sagas/employeeSaga.js
  src/main/frontend/src/store/sagas/employeesSaga.js
  src/main/frontend/src/store/sagas/teamSaga.js
  src/main/frontend/src/store/selectors.js
  src/main/frontend/src/store/services/employeeService.js
  src/main/frontend/src/store/services/teamService.js
  src/main/frontend/yarn.lock
  src/main/java/eu/execom/hawaii/api/controller/UserController.java
  src/main/java/eu/execom/hawaii/repository/UserRepository.java
  src/main/java/eu/execom/hawaii/service/UserService.java
  src/main/resources/application.properties.example
  src/main/resources/liquibase.properties
Labels: enhancement, frontend

#178 Overwrite new or removed users from team fix
  src/main/java/eu/execom/hawaii/service/TeamService.java
Labels: backend, fix

#177 Add email notifiers for Sickness, Annual and Bonus request
  src/main/java/eu/execom/hawaii/dto/TeamDto.java
  src/main/java/eu/execom/hawaii/model/Team.java
  src/main/java/eu/execom/hawaii/model/audit/TeamAudit.java
  src/main/java/eu/execom/hawaii/service/EmailService.java
  src/main/java/eu/execom/hawaii/service/RequestService.java
  src/main/java/eu/execom/hawaii/util/EmailSubjectProvider.java
  src/main/resources/DataScript01022019.sql
  src/main/resources/db/changelog/initialDbSchema.xml
  src/main/resources/templates/recipientsAnnualEmail.ftl
  src/main/resources/templates/recipientsBonusEmail.ftl
  src/main/resources/templates/recipientsSicknessEmail.ftl
  src/test/java/eu/execom/hawaii/service/EntityBuilder.java
  src/test/java/eu/execom/hawaii/service/RequestServiceTest.java
Labels: backend, enhancement

#169 B feature/get user by id
  src/main/java/eu/execom/hawaii/api/controller/UserController.java
  src/main/java/eu/execom/hawaii/model/Team.java
  src/main/java/eu/execom/hawaii/service/RequestService.java
Labels: backend

#175 Create user fix, modifiedUser is non existent for CREATE operation.
  src/main/java/eu/execom/hawaii/service/UserService.java
Labels: backend, fix

#179 Remove Team
  images/hawaii.png
  src/main/java/eu/execom/hawaii/api/controller/GlobalExceptionHandler.java
  src/main/java/eu/execom/hawaii/api/controller/TeamController.java
  src/main/java/eu/execom/hawaii/dto/TeamDto.java
  src/main/java/eu/execom/hawaii/exceptions/ActionNotAllowedException.java
  src/main/java/eu/execom/hawaii/exceptions/NotAuthorizedApprovalException.java
  src/main/java/eu/execom/hawaii/model/Team.java
  src/main/java/eu/execom/hawaii/model/audit/TeamAudit.java
  src/main/java/eu/execom/hawaii/repository/TeamRepository.java
  src/main/java/eu/execom/hawaii/service/RequestService.java
  src/main/java/eu/execom/hawaii/service/TeamService.java
  src/main/resources/DataScript01022019.sql
  src/test/java/eu/execom/hawaii/service/EntityBuilder.java
  src/test/java/eu/execom/hawaii/service/RequestServiceTest.java
  src/test/java/eu/execom/hawaii/service/TeamServiceTest.java
Labels: backend

#182 Api security test fix
  src/test/java/eu/execom/hawaii/security/ApiSecurityTests.java
Labels: backend

#184 B fix/develop missingcode restore
  images/hawaii.png
  pom.xml
  src/main/java/eu/execom/hawaii/api/controller/UserController.java
  src/main/java/eu/execom/hawaii/repository/UserRepository.java
  src/main/java/eu/execom/hawaii/service/UserService.java
  src/main/resources/application.properties.example
  src/main/resources/liquibase.properties
Labels: backend, fix

#185 Fix liquibase naming requirements
  src/main/resources/db/changelog/initialDbSchema.xml
Labels: backend, fix

#187 b-feature/merging-frontend-and-backend
  images/hawaii.png
  pom.xml
  src/main/frontend/package.json
  src/main/frontend/public/favicon.png
  src/main/frontend/public/index.html
  src/main/frontend/src/App.js
  src/main/frontend/src/env.js
  src/main/frontend/src/store/getLink.js
  src/main/frontend/src/store/services/employeeService.js
  src/main/frontend/src/store/services/employeesService.js
  src/main/frontend/src/store/services/getTokenRequest.js
  src/main/frontend/src/store/services/teamService.js
  src/main/frontend/src/store/services/teamsService.js
  src/main/frontend/src/store/services/userService.js
  src/main/frontend/yarn.lock
  src/main/java/eu/execom/hawaii/configuration/WebConfig.java
  src/main/java/eu/execom/hawaii/security/SecurityConfiguration.java
  src/test/java/eu/execom/hawaii/service/DayServiceTest.java
Labels: backend, frontend

#186 get user by email controller mapping fix
  src/main/java/eu/execom/hawaii/api/controller/UserController.java
Labels: backend

#189 get user Allowance for year and get Logged user Allowance for year
  src/main/java/eu/execom/hawaii/api/controller/AllowanceController.java
  src/main/java/eu/execom/hawaii/service/AllowanceService.java
Labels: backend

#188 get user requests by year and get logged user requests by year
  src/main/java/eu/execom/hawaii/api/controller/RequestController.java
  src/main/java/eu/execom/hawaii/service/RequestService.java
Labels: backend

#191 b-feature/merging-frontend-and-backend
  images/hawaii.png
  pom.xml
Labels: backend, fix, frontend

#193 Remove sensitive information, update readme file
  README.md
  src/main/resources/DataScript01022019.sql
  src/main/resources/application.properties.example
Labels: backend, fix

#195 method name changed
  src/main/java/eu/execom/hawaii/api/controller/AllowanceController.java
Labels: backend

#160 B feature/team search
  src/main/java/eu/execom/hawaii/api/controller/TeamController.java
  src/main/java/eu/execom/hawaii/repository/UserRepository.java
  src/main/java/eu/execom/hawaii/service/TeamService.java
  src/main/java/eu/execom/hawaii/service/UserService.java
Labels: backend

#196 Refactor CarryOverVacationJob, improve test coverage
  src/main/java/eu/execom/hawaii/jobs/CarryOverVacationJob.java
  src/main/java/eu/execom/hawaii/service/AllowanceService.java
  src/test/java/eu/execom/hawaii/jobs/CarryOverVacationJobTest.java
Labels: backend, fix

#197 Add default values, minimum required query size
  src/main/java/eu/execom/hawaii/api/controller/UserController.java
  src/main/java/eu/execom/hawaii/service/UserService.java
Labels: backend, fix

#194 B fix/update team members
  src/main/java/eu/execom/hawaii/service/TeamService.java
  src/main/resources/db/changelog/initialDbSchema.xml
Labels: backend

#199 Change delete team exception handling, remove unnecessary lines
  src/main/java/eu/execom/hawaii/api/controller/GlobalExceptionHandler.java
  src/main/java/eu/execom/hawaii/api/controller/TeamController.java
  src/main/java/eu/execom/hawaii/exceptions/ActionNotAllowedException.java
  src/main/java/eu/execom/hawaii/service/TeamService.java
Labels: backend, fix

#192 f-feature/gh-190-error-handling
  src/main/frontend/package.json
  src/main/frontend/public/index.html
  src/main/frontend/src/components/dashboard/Dashboard.js
  src/main/frontend/src/index.js
  src/main/frontend/src/store/reducers/reducers.js
  src/main/frontend/src/store/sagas/getTokenSaga.js
  src/main/frontend/src/store/sagas/userSaga.js
  src/main/frontend/src/store/services/userService.js
Labels: enhancement, frontend

#202 Add access through security for icons/** path
  src/main/java/eu/execom/hawaii/security/SecurityConfiguration.java
Labels: backend, fix
