Repository execom-eu/hawaii, pull requests merged in 2019-01, with the labels that each got.

#138 B fix/user add start working day
  src/main/java/eu/execom/hawaii/dto/UserDto.java
  src/main/java/eu/execom/hawaii/jobs/CarryOverVacationJob.java
  src/main/java/eu/execom/hawaii/jobs/IncrementServiceYearsJob.java
  src/main/java/eu/execom/hawaii/model/User.java
  src/main/java/eu/execom/hawaii/service/EmailService.java
  src/main/java/eu/execom/hawaii/service/UserService.java
  src/main/java/eu/execom/hawaii/util/EmailSubjectProvider.java
  src/main/resources/db/changelog/initialDbSchema.xml
  src/main/resources/templates/userLeaveProfileUpdate.ftl
  src/test/java/eu/execom/hawaii/jobs/CarryOverVacationJobTest.java
  src/test/java/eu/execom/hawaii/jobs/IncrementServiceYearsJobTest.java
  src/test/java/eu/execom/hawaii/service/AllowanceServiceTest.java
  src/test/java/eu/execom/hawaii/service/EntityBuilder.java
  src/test/java/eu/execom/hawaii/service/RequestServiceTest.java
  src/test/java/eu/execom/hawaii/service/UserServiceTest.java
  src/test/java/eu/execom/hawaii/service/YearServiceTest.java
Labels: backend, fix

#142 B-fix/pom_fix
  images/hawaii.png
  pom.xml
Labels: backend, bug

#143 B feature/me api
  .gitignore
  README.md
  pom.xml
  src/main/frontend/src/store/services/getTokenRequest.js
  src/main/frontend/src/store/store.js
  src/main/java/eu/execom/hawaii/api/controller/UserController.java
  src/main/java/eu/execom/hawaii/jobs/IncrementServiceYearsJob.java
  src/main/java/eu/execom/hawaii/model/User.java
  src/main/java/eu/execom/hawaii/security/IdTokenVerifierFilter.java
  src/main/java/eu/execom/hawaii/security/SecurityConfiguration.java
  src/main/resources/application.properties.example
  src/test/java/eu/execom/hawaii/service/EntityBuilder.java
Labels: backend, bug, enhancement

#139 B feature/add allowanceForUserDto
  src/main/java/eu/execom/hawaii/api/controller/AllowanceController.java
  src/main/java/eu/execom/hawaii/api/controller/UserController.java
  src/main/java/eu/execom/hawaii/dto/AllowanceForUserDto.java
  src/main/java/eu/execom/hawaii/dto/AllowanceWithoutYearDto.java
  src/main/java/eu/execom/hawaii/dto/YearDto.java
  src/main/java/eu/execom/hawaii/jobs/CarryOverVacationJob.java
  src/main/java/eu/execom/hawaii/repository/AllowanceRepository.java
  src/main/java/eu/execom/hawaii/service/AllowanceService.java
  src/main/resources/application.properties.example
  src/main/resources/db/changelog/initialDbSchema.xml
  src/test/java/eu/execom/hawaii/jobs/CarryOverVacationJobTest.java
  src/test/java/eu/execom/hawaii/service/AllowanceServiceTest.java
Labels: backend, enhancement

#144 B feature/add leave profile type
  src/main/java/eu/execom/hawaii/api/controller/LeaveProfileController.java
  src/main/java/eu/execom/hawaii/dto/LeaveProfileDto.java
  src/main/java/eu/execom/hawaii/jobs/IncrementServiceYearsJob.java
  src/main/java/eu/execom/hawaii/model/LeaveProfile.java
  src/main/java/eu/execom/hawaii/model/enumerations/LeaveProfileType.java
  src/main/java/eu/execom/hawaii/repository/LeaveProfileRepository.java
  src/main/java/eu/execom/hawaii/service/LeaveProfileService.java
  src/main/java/eu/execom/hawaii/service/UserService.java
  src/main/resources/db/changelog/initialDbSchema.xml
  src/test/java/eu/execom/hawaii/jobs/IncrementServiceYearsJobTest.java
  src/test/java/eu/execom/hawaii/service/EntityBuilder.java
  src/test/java/eu/execom/hawaii/service/UserServiceTest.java
Labels: backend, enhancement

#136 Global styling and structure changes
  src/main/frontend/src/components/common/navigationLink.js
  src/main/frontend/src/components/header/TopHeader.js
  src/main/frontend/src/components/navigation/Sidebar.js
  src/main/frontend/src/img/hawaii_wallpaper.jpg
  src/main/frontend/src/layout/Login.js
  src/main/frontend/src/layout/Panel.js
  src/main/frontend/src/styles/globalStyles.js
Labels: enhancement, frontend
